kind: pipeline
type: exec
name: backend-builder

platform:
  os: linux
  arch: amd64

steps:
  - name: building-image
    commands:
      - docker build -t backend:latest .

trigger:
  branch: 
    - master
  event:
    - tag